name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checks:
    name: Run Checks
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
 
      - name: Build
        run: pnpm run build

      - name: Check Types
        run: pnpm run check-types

      - name: Test
        run: pnpm run test

  deploy:
    name: Deploy Apps
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - name: Deploy Message Service
        run: |
          export APP_IDS=${{ secrets.MESSAGE_SERVICE_APP_ID }}
          export FULL_URL="https://coolify.pacon.dev/api/v1/deploy?uuid=$APP_IDS"
          curl \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_TOKEN }}" \
            "$FULL_URL"
